// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: session/session.proto

package sessionpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Envelope_ChannelOpen
	//	*Envelope_ChannelOpenResult
	//	*Envelope_ChannelData
	//	*Envelope_ChannelWindowAdjust
	//	*Envelope_ChannelEof
	//	*Envelope_ChannelClose
	//	*Envelope_ChannelRequest
	//	*Envelope_ChannelResult
	//	*Envelope_GlobalRequest
	//	*Envelope_GlobalResult
	//	*Envelope_Disconnect
	Kind          isEnvelope_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetKind() isEnvelope_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Envelope) GetChannelOpen() *ChannelOpen {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelOpen); ok {
			return x.ChannelOpen
		}
	}
	return nil
}

func (x *Envelope) GetChannelOpenResult() *ChannelOpenResult {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelOpenResult); ok {
			return x.ChannelOpenResult
		}
	}
	return nil
}

func (x *Envelope) GetChannelData() *ChannelData {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelData); ok {
			return x.ChannelData
		}
	}
	return nil
}

func (x *Envelope) GetChannelWindowAdjust() *ChannelWindowAdjust {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelWindowAdjust); ok {
			return x.ChannelWindowAdjust
		}
	}
	return nil
}

func (x *Envelope) GetChannelEof() *ChannelEof {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelEof); ok {
			return x.ChannelEof
		}
	}
	return nil
}

func (x *Envelope) GetChannelClose() *ChannelClose {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelClose); ok {
			return x.ChannelClose
		}
	}
	return nil
}

func (x *Envelope) GetChannelRequest() *ChannelRequest {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelRequest); ok {
			return x.ChannelRequest
		}
	}
	return nil
}

func (x *Envelope) GetChannelResult() *ChannelResult {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ChannelResult); ok {
			return x.ChannelResult
		}
	}
	return nil
}

func (x *Envelope) GetGlobalRequest() *GlobalRequest {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_GlobalRequest); ok {
			return x.GlobalRequest
		}
	}
	return nil
}

func (x *Envelope) GetGlobalResult() *GlobalResult {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_GlobalResult); ok {
			return x.GlobalResult
		}
	}
	return nil
}

func (x *Envelope) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isEnvelope_Kind interface {
	isEnvelope_Kind()
}

type Envelope_ChannelOpen struct {
	ChannelOpen *ChannelOpen `protobuf:"bytes,1,opt,name=channel_open,json=channelOpen,proto3,oneof"`
}

type Envelope_ChannelOpenResult struct {
	ChannelOpenResult *ChannelOpenResult `protobuf:"bytes,2,opt,name=channel_open_result,json=channelOpenResult,proto3,oneof"`
}

type Envelope_ChannelData struct {
	ChannelData *ChannelData `protobuf:"bytes,3,opt,name=channel_data,json=channelData,proto3,oneof"`
}

type Envelope_ChannelWindowAdjust struct {
	ChannelWindowAdjust *ChannelWindowAdjust `protobuf:"bytes,4,opt,name=channel_window_adjust,json=channelWindowAdjust,proto3,oneof"`
}

type Envelope_ChannelEof struct {
	ChannelEof *ChannelEof `protobuf:"bytes,5,opt,name=channel_eof,json=channelEof,proto3,oneof"`
}

type Envelope_ChannelClose struct {
	ChannelClose *ChannelClose `protobuf:"bytes,6,opt,name=channel_close,json=channelClose,proto3,oneof"`
}

type Envelope_ChannelRequest struct {
	ChannelRequest *ChannelRequest `protobuf:"bytes,7,opt,name=channel_request,json=channelRequest,proto3,oneof"`
}

type Envelope_ChannelResult struct {
	ChannelResult *ChannelResult `protobuf:"bytes,8,opt,name=channel_result,json=channelResult,proto3,oneof"`
}

type Envelope_GlobalRequest struct {
	GlobalRequest *GlobalRequest `protobuf:"bytes,9,opt,name=global_request,json=globalRequest,proto3,oneof"`
}

type Envelope_GlobalResult struct {
	GlobalResult *GlobalResult `protobuf:"bytes,10,opt,name=global_result,json=globalResult,proto3,oneof"`
}

type Envelope_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,11,opt,name=disconnect,proto3,oneof"`
}

func (*Envelope_ChannelOpen) isEnvelope_Kind() {}

func (*Envelope_ChannelOpenResult) isEnvelope_Kind() {}

func (*Envelope_ChannelData) isEnvelope_Kind() {}

func (*Envelope_ChannelWindowAdjust) isEnvelope_Kind() {}

func (*Envelope_ChannelEof) isEnvelope_Kind() {}

func (*Envelope_ChannelClose) isEnvelope_Kind() {}

func (*Envelope_ChannelRequest) isEnvelope_Kind() {}

func (*Envelope_ChannelResult) isEnvelope_Kind() {}

func (*Envelope_GlobalRequest) isEnvelope_Kind() {}

func (*Envelope_GlobalResult) isEnvelope_Kind() {}

func (*Envelope_Disconnect) isEnvelope_Kind() {}

type ChannelOpen struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelType     string                 `protobuf:"bytes,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	SenderChannelId uint64                 `protobuf:"varint,2,opt,name=sender_channel_id,json=senderChannelId,proto3" json:"sender_channel_id,omitempty"`
	InitialWindow   uint32                 `protobuf:"varint,3,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	MaxPacketSize   uint32                 `protobuf:"varint,4,opt,name=max_packet_size,json=maxPacketSize,proto3" json:"max_packet_size,omitempty"`
	Payload         []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelOpen) Reset() {
	*x = ChannelOpen{}
	mi := &file_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpen) ProtoMessage() {}

func (x *ChannelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpen.ProtoReflect.Descriptor instead.
func (*ChannelOpen) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelOpen) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *ChannelOpen) GetSenderChannelId() uint64 {
	if x != nil {
		return x.SenderChannelId
	}
	return 0
}

func (x *ChannelOpen) GetInitialWindow() uint32 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

func (x *ChannelOpen) GetMaxPacketSize() uint32 {
	if x != nil {
		return x.MaxPacketSize
	}
	return 0
}

func (x *ChannelOpen) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ChannelOpenResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ChannelOpenResult_Success
	//	*ChannelOpenResult_Reject
	Result        isChannelOpenResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelOpenResult) Reset() {
	*x = ChannelOpenResult{}
	mi := &file_session_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOpenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenResult) ProtoMessage() {}

func (x *ChannelOpenResult) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenResult.ProtoReflect.Descriptor instead.
func (*ChannelOpenResult) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelOpenResult) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

func (x *ChannelOpenResult) GetResult() isChannelOpenResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ChannelOpenResult) GetSuccess() *ChannelOpenAccept {
	if x != nil {
		if x, ok := x.Result.(*ChannelOpenResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ChannelOpenResult) GetReject() *ChannelOpenReject {
	if x != nil {
		if x, ok := x.Result.(*ChannelOpenResult_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isChannelOpenResult_Result interface {
	isChannelOpenResult_Result()
}

type ChannelOpenResult_Success struct {
	Success *ChannelOpenAccept `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type ChannelOpenResult_Reject struct {
	Reject *ChannelOpenReject `protobuf:"bytes,3,opt,name=reject,proto3,oneof"`
}

func (*ChannelOpenResult_Success) isChannelOpenResult_Result() {}

func (*ChannelOpenResult_Reject) isChannelOpenResult_Result() {}

type ChannelOpenAccept struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderChannelId uint64                 `protobuf:"varint,1,opt,name=sender_channel_id,json=senderChannelId,proto3" json:"sender_channel_id,omitempty"`
	InitialWindow   uint32                 `protobuf:"varint,2,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	MaxPacketSize   uint32                 `protobuf:"varint,3,opt,name=max_packet_size,json=maxPacketSize,proto3" json:"max_packet_size,omitempty"`
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelOpenAccept) Reset() {
	*x = ChannelOpenAccept{}
	mi := &file_session_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOpenAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenAccept) ProtoMessage() {}

func (x *ChannelOpenAccept) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenAccept.ProtoReflect.Descriptor instead.
func (*ChannelOpenAccept) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelOpenAccept) GetSenderChannelId() uint64 {
	if x != nil {
		return x.SenderChannelId
	}
	return 0
}

func (x *ChannelOpenAccept) GetInitialWindow() uint32 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

func (x *ChannelOpenAccept) GetMaxPacketSize() uint32 {
	if x != nil {
		return x.MaxPacketSize
	}
	return 0
}

func (x *ChannelOpenAccept) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ChannelOpenReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelOpenReject) Reset() {
	*x = ChannelOpenReject{}
	mi := &file_session_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOpenReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenReject) ProtoMessage() {}

func (x *ChannelOpenReject) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenReject.ProtoReflect.Descriptor instead.
func (*ChannelOpenReject) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelOpenReject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ChannelOpenReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChannelOpenReject) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ChannelData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	Data               []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelData) Reset() {
	*x = ChannelData{}
	mi := &file_session_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelData) ProtoMessage() {}

func (x *ChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelData.ProtoReflect.Descriptor instead.
func (*ChannelData) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelData) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

func (x *ChannelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChannelWindowAdjust struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	BytesToAdd         uint32                 `protobuf:"varint,2,opt,name=bytes_to_add,json=bytesToAdd,proto3" json:"bytes_to_add,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelWindowAdjust) Reset() {
	*x = ChannelWindowAdjust{}
	mi := &file_session_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelWindowAdjust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelWindowAdjust) ProtoMessage() {}

func (x *ChannelWindowAdjust) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelWindowAdjust.ProtoReflect.Descriptor instead.
func (*ChannelWindowAdjust) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelWindowAdjust) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

func (x *ChannelWindowAdjust) GetBytesToAdd() uint32 {
	if x != nil {
		return x.BytesToAdd
	}
	return 0
}

type ChannelEof struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelEof) Reset() {
	*x = ChannelEof{}
	mi := &file_session_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelEof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelEof) ProtoMessage() {}

func (x *ChannelEof) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelEof.ProtoReflect.Descriptor instead.
func (*ChannelEof) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelEof) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

type ChannelClose struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelClose) Reset() {
	*x = ChannelClose{}
	mi := &file_session_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelClose) ProtoMessage() {}

func (x *ChannelClose) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelClose.ProtoReflect.Descriptor instead.
func (*ChannelClose) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelClose) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

type ChannelRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	RequestId          uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestType        string                 `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	WantReply          bool                   `protobuf:"varint,4,opt,name=want_reply,json=wantReply,proto3" json:"want_reply,omitempty"`
	Payload            []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChannelRequest) Reset() {
	*x = ChannelRequest{}
	mi := &file_session_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRequest) ProtoMessage() {}

func (x *ChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRequest.ProtoReflect.Descriptor instead.
func (*ChannelRequest) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelRequest) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

func (x *ChannelRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChannelRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *ChannelRequest) GetWantReply() bool {
	if x != nil {
		return x.WantReply
	}
	return false
}

func (x *ChannelRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ChannelResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecipientChannelId uint64                 `protobuf:"varint,1,opt,name=recipient_channel_id,json=recipientChannelId,proto3" json:"recipient_channel_id,omitempty"`
	RequestId          uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ChannelResult_Success
	//	*ChannelResult_Reject
	Result        isChannelResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResult) Reset() {
	*x = ChannelResult{}
	mi := &file_session_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResult) ProtoMessage() {}

func (x *ChannelResult) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResult.ProtoReflect.Descriptor instead.
func (*ChannelResult) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{10}
}

func (x *ChannelResult) GetRecipientChannelId() uint64 {
	if x != nil {
		return x.RecipientChannelId
	}
	return 0
}

func (x *ChannelResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChannelResult) GetResult() isChannelResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ChannelResult) GetSuccess() *OperationSuccess {
	if x != nil {
		if x, ok := x.Result.(*ChannelResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ChannelResult) GetReject() *OperationReject {
	if x != nil {
		if x, ok := x.Result.(*ChannelResult_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isChannelResult_Result interface {
	isChannelResult_Result()
}

type ChannelResult_Success struct {
	Success *OperationSuccess `protobuf:"bytes,3,opt,name=success,proto3,oneof"`
}

type ChannelResult_Reject struct {
	Reject *OperationReject `protobuf:"bytes,4,opt,name=reject,proto3,oneof"`
}

func (*ChannelResult_Success) isChannelResult_Result() {}

func (*ChannelResult_Reject) isChannelResult_Result() {}

type GlobalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestType   string                 `protobuf:"bytes,2,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	WantReply     bool                   `protobuf:"varint,3,opt,name=want_reply,json=wantReply,proto3" json:"want_reply,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalRequest) Reset() {
	*x = GlobalRequest{}
	mi := &file_session_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalRequest) ProtoMessage() {}

func (x *GlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalRequest.ProtoReflect.Descriptor instead.
func (*GlobalRequest) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{11}
}

func (x *GlobalRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GlobalRequest) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *GlobalRequest) GetWantReply() bool {
	if x != nil {
		return x.WantReply
	}
	return false
}

func (x *GlobalRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GlobalResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GlobalResult_Success
	//	*GlobalResult_Reject
	Result        isGlobalResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalResult) Reset() {
	*x = GlobalResult{}
	mi := &file_session_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalResult) ProtoMessage() {}

func (x *GlobalResult) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalResult.ProtoReflect.Descriptor instead.
func (*GlobalResult) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{12}
}

func (x *GlobalResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GlobalResult) GetResult() isGlobalResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GlobalResult) GetSuccess() *OperationSuccess {
	if x != nil {
		if x, ok := x.Result.(*GlobalResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *GlobalResult) GetReject() *OperationReject {
	if x != nil {
		if x, ok := x.Result.(*GlobalResult_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isGlobalResult_Result interface {
	isGlobalResult_Result()
}

type GlobalResult_Success struct {
	Success *OperationSuccess `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type GlobalResult_Reject struct {
	Reject *OperationReject `protobuf:"bytes,3,opt,name=reject,proto3,oneof"`
}

func (*GlobalResult_Success) isGlobalResult_Result() {}

func (*GlobalResult_Reject) isGlobalResult_Result() {}

type OperationSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationSuccess) Reset() {
	*x = OperationSuccess{}
	mi := &file_session_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationSuccess) ProtoMessage() {}

func (x *OperationSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationSuccess.ProtoReflect.Descriptor instead.
func (*OperationSuccess) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{13}
}

func (x *OperationSuccess) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OperationReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationReject) Reset() {
	*x = OperationReject{}
	mi := &file_session_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationReject) ProtoMessage() {}

func (x *OperationReject) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationReject.ProtoReflect.Descriptor instead.
func (*OperationReject) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{14}
}

func (x *OperationReject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OperationReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationReject) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_session_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{15}
}

func (x *Disconnect) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Disconnect) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_session_session_proto protoreflect.FileDescriptor

const file_session_session_proto_rawDesc = "" +
	"\n" +
	"\x15session/session.proto\x12\asession\x1a\x1bbuf/validate/validate.proto\"\xe2\x05\n" +
	"\bEnvelope\x129\n" +
	"\fchannel_open\x18\x01 \x01(\v2\x14.session.ChannelOpenH\x00R\vchannelOpen\x12L\n" +
	"\x13channel_open_result\x18\x02 \x01(\v2\x1a.session.ChannelOpenResultH\x00R\x11channelOpenResult\x129\n" +
	"\fchannel_data\x18\x03 \x01(\v2\x14.session.ChannelDataH\x00R\vchannelData\x12R\n" +
	"\x15channel_window_adjust\x18\x04 \x01(\v2\x1c.session.ChannelWindowAdjustH\x00R\x13channelWindowAdjust\x126\n" +
	"\vchannel_eof\x18\x05 \x01(\v2\x13.session.ChannelEofH\x00R\n" +
	"channelEof\x12<\n" +
	"\rchannel_close\x18\x06 \x01(\v2\x15.session.ChannelCloseH\x00R\fchannelClose\x12B\n" +
	"\x0fchannel_request\x18\a \x01(\v2\x17.session.ChannelRequestH\x00R\x0echannelRequest\x12?\n" +
	"\x0echannel_result\x18\b \x01(\v2\x16.session.ChannelResultH\x00R\rchannelResult\x12?\n" +
	"\x0eglobal_request\x18\t \x01(\v2\x16.session.GlobalRequestH\x00R\rglobalRequest\x12<\n" +
	"\rglobal_result\x18\n" +
	" \x01(\v2\x15.session.GlobalResultH\x00R\fglobalResult\x125\n" +
	"\n" +
	"disconnect\x18\v \x01(\v2\x13.session.DisconnectH\x00R\n" +
	"disconnectB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\xe0\x01\n" +
	"\vChannelOpen\x12*\n" +
	"\fchannel_type\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vchannelType\x12*\n" +
	"\x11sender_channel_id\x18\x02 \x01(\x04R\x0fsenderChannelId\x12.\n" +
	"\x0einitial_window\x18\x03 \x01(\rB\a\xbaH\x04*\x02 \x00R\rinitialWindow\x12/\n" +
	"\x0fmax_packet_size\x18\x04 \x01(\rB\a\xbaH\x04*\x02 \x00R\rmaxPacketSize\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xc4\x01\n" +
	"\x11ChannelOpenResult\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\x126\n" +
	"\asuccess\x18\x02 \x01(\v2\x1a.session.ChannelOpenAcceptH\x00R\asuccess\x124\n" +
	"\x06reject\x18\x03 \x01(\v2\x1a.session.ChannelOpenRejectH\x00R\x06rejectB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\xba\x01\n" +
	"\x11ChannelOpenAccept\x12*\n" +
	"\x11sender_channel_id\x18\x01 \x01(\x04R\x0fsenderChannelId\x12.\n" +
	"\x0einitial_window\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\rinitialWindow\x12/\n" +
	"\x0fmax_packet_size\x18\x03 \x01(\rB\a\xbaH\x04*\x02 \x00R\rmaxPacketSize\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"d\n" +
	"\x11ChannelOpenReject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"S\n" +
	"\vChannelData\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"r\n" +
	"\x13ChannelWindowAdjust\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\x12)\n" +
	"\fbytes_to_add\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\n" +
	"bytesToAdd\">\n" +
	"\n" +
	"ChannelEof\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\"@\n" +
	"\fChannelClose\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\"\xc6\x01\n" +
	"\x0eChannelRequest\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12*\n" +
	"\frequest_type\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vrequestType\x12\x1d\n" +
	"\n" +
	"want_reply\x18\x04 \x01(\bR\twantReply\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xdc\x01\n" +
	"\rChannelResult\x120\n" +
	"\x14recipient_channel_id\x18\x01 \x01(\x04R\x12recipientChannelId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x125\n" +
	"\asuccess\x18\x03 \x01(\v2\x19.session.OperationSuccessH\x00R\asuccess\x122\n" +
	"\x06reject\x18\x04 \x01(\v2\x18.session.OperationRejectH\x00R\x06rejectB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\x93\x01\n" +
	"\rGlobalRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12*\n" +
	"\frequest_type\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vrequestType\x12\x1d\n" +
	"\n" +
	"want_reply\x18\x03 \x01(\bR\twantReply\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xa9\x01\n" +
	"\fGlobalResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x125\n" +
	"\asuccess\x18\x02 \x01(\v2\x19.session.OperationSuccessH\x00R\asuccess\x122\n" +
	"\x06reject\x18\x03 \x01(\v2\x18.session.OperationRejectH\x00R\x06rejectB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\",\n" +
	"\x10OperationSuccess\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"b\n" +
	"\x0fOperationReject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"C\n" +
	"\n" +
	"Disconnect\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessageB<Z:github.com/Mikadore/mygosh/lib/session/sessionpb;sessionpbb\x06proto3"

var (
	file_session_session_proto_rawDescOnce sync.Once
	file_session_session_proto_rawDescData []byte
)

func file_session_session_proto_rawDescGZIP() []byte {
	file_session_session_proto_rawDescOnce.Do(func() {
		file_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_session_proto_rawDesc), len(file_session_session_proto_rawDesc)))
	})
	return file_session_session_proto_rawDescData
}

var file_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_session_session_proto_goTypes = []any{
	(*Envelope)(nil),            // 0: session.Envelope
	(*ChannelOpen)(nil),         // 1: session.ChannelOpen
	(*ChannelOpenResult)(nil),   // 2: session.ChannelOpenResult
	(*ChannelOpenAccept)(nil),   // 3: session.ChannelOpenAccept
	(*ChannelOpenReject)(nil),   // 4: session.ChannelOpenReject
	(*ChannelData)(nil),         // 5: session.ChannelData
	(*ChannelWindowAdjust)(nil), // 6: session.ChannelWindowAdjust
	(*ChannelEof)(nil),          // 7: session.ChannelEof
	(*ChannelClose)(nil),        // 8: session.ChannelClose
	(*ChannelRequest)(nil),      // 9: session.ChannelRequest
	(*ChannelResult)(nil),       // 10: session.ChannelResult
	(*GlobalRequest)(nil),       // 11: session.GlobalRequest
	(*GlobalResult)(nil),        // 12: session.GlobalResult
	(*OperationSuccess)(nil),    // 13: session.OperationSuccess
	(*OperationReject)(nil),     // 14: session.OperationReject
	(*Disconnect)(nil),          // 15: session.Disconnect
}
var file_session_session_proto_depIdxs = []int32{
	1,  // 0: session.Envelope.channel_open:type_name -> session.ChannelOpen
	2,  // 1: session.Envelope.channel_open_result:type_name -> session.ChannelOpenResult
	5,  // 2: session.Envelope.channel_data:type_name -> session.ChannelData
	6,  // 3: session.Envelope.channel_window_adjust:type_name -> session.ChannelWindowAdjust
	7,  // 4: session.Envelope.channel_eof:type_name -> session.ChannelEof
	8,  // 5: session.Envelope.channel_close:type_name -> session.ChannelClose
	9,  // 6: session.Envelope.channel_request:type_name -> session.ChannelRequest
	10, // 7: session.Envelope.channel_result:type_name -> session.ChannelResult
	11, // 8: session.Envelope.global_request:type_name -> session.GlobalRequest
	12, // 9: session.Envelope.global_result:type_name -> session.GlobalResult
	15, // 10: session.Envelope.disconnect:type_name -> session.Disconnect
	3,  // 11: session.ChannelOpenResult.success:type_name -> session.ChannelOpenAccept
	4,  // 12: session.ChannelOpenResult.reject:type_name -> session.ChannelOpenReject
	13, // 13: session.ChannelResult.success:type_name -> session.OperationSuccess
	14, // 14: session.ChannelResult.reject:type_name -> session.OperationReject
	13, // 15: session.GlobalResult.success:type_name -> session.OperationSuccess
	14, // 16: session.GlobalResult.reject:type_name -> session.OperationReject
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_session_session_proto_init() }
func file_session_session_proto_init() {
	if File_session_session_proto != nil {
		return
	}
	file_session_session_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_ChannelOpen)(nil),
		(*Envelope_ChannelOpenResult)(nil),
		(*Envelope_ChannelData)(nil),
		(*Envelope_ChannelWindowAdjust)(nil),
		(*Envelope_ChannelEof)(nil),
		(*Envelope_ChannelClose)(nil),
		(*Envelope_ChannelRequest)(nil),
		(*Envelope_ChannelResult)(nil),
		(*Envelope_GlobalRequest)(nil),
		(*Envelope_GlobalResult)(nil),
		(*Envelope_Disconnect)(nil),
	}
	file_session_session_proto_msgTypes[2].OneofWrappers = []any{
		(*ChannelOpenResult_Success)(nil),
		(*ChannelOpenResult_Reject)(nil),
	}
	file_session_session_proto_msgTypes[10].OneofWrappers = []any{
		(*ChannelResult_Success)(nil),
		(*ChannelResult_Reject)(nil),
	}
	file_session_session_proto_msgTypes[12].OneofWrappers = []any{
		(*GlobalResult_Success)(nil),
		(*GlobalResult_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_session_proto_rawDesc), len(file_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_session_proto_goTypes,
		DependencyIndexes: file_session_session_proto_depIdxs,
		MessageInfos:      file_session_session_proto_msgTypes,
	}.Build()
	File_session_session_proto = out.File
	file_session_session_proto_goTypes = nil
	file_session_session_proto_depIdxs = nil
}
