services:
  server:
    image: mygosh-server:dev
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    init: true
    ports:
      - "42022:42022"
    volumes:
      - type: bind
        source: ${HOME}/.mygosh
        target: /root/.mygosh
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - build/
            - dist/
            - mygosh.toml

        - action: sync+restart
          path: ./mygosh.toml
          target: /workspace/mygosh.toml
          initial_sync: true
