[listen]
address = "localhost:42022"

[daemon]
max_connections = 32
max_connections_per_ip = 4
shutdown_timeout = "5s"

[identity]
host_key = "~/.mygosh/host_ed25519"

[authorization]
authorized_keys = [
  "~/.mygosh/authorized_keys",
  "~/.ssh/authorized_keys",
]

[authorization.permissions]
allow_shell = true
allow_exec = true
allow_pty = true
allowed_environment = ["TERM", "COLORTERM", "LANG", "LC_ALL", "LC_CTYPE"]

[log]
# One of: DEBUG INFO WARN ERROR FATAL NONE
level = "DEBUG"

# Output console logs as JSON
json = false

# Append structured JSON logs to this file
file = "mygosh-server.log"
