[core]
host = "localhost"
port = 42022
shell = "/bin/bash"

[log]
# One of: DEBUG INFO WARN ERROR FATAL NONE
level = "DEBUG"

# Output console logs as JSON
json = false

# Append structured JSON logs to this file
file = "mygosh.log"
