// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/auth.proto

package authpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AuthFrame_HostAuthInit
	//	*AuthFrame_ServerAuth
	//	*AuthFrame_ClientAuthRequest
	//	*AuthFrame_ClientAuthResponse
	//	*AuthFrame_Error
	Kind          isAuthFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthFrame) Reset() {
	*x = AuthFrame{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFrame) ProtoMessage() {}

func (x *AuthFrame) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFrame.ProtoReflect.Descriptor instead.
func (*AuthFrame) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthFrame) GetKind() isAuthFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AuthFrame) GetHostAuthInit() *HostAuthInit {
	if x != nil {
		if x, ok := x.Kind.(*AuthFrame_HostAuthInit); ok {
			return x.HostAuthInit
		}
	}
	return nil
}

func (x *AuthFrame) GetServerAuth() *ServerAuth {
	if x != nil {
		if x, ok := x.Kind.(*AuthFrame_ServerAuth); ok {
			return x.ServerAuth
		}
	}
	return nil
}

func (x *AuthFrame) GetClientAuthRequest() *ClientAuthRequest {
	if x != nil {
		if x, ok := x.Kind.(*AuthFrame_ClientAuthRequest); ok {
			return x.ClientAuthRequest
		}
	}
	return nil
}

func (x *AuthFrame) GetClientAuthResponse() *ClientAuthResponse {
	if x != nil {
		if x, ok := x.Kind.(*AuthFrame_ClientAuthResponse); ok {
			return x.ClientAuthResponse
		}
	}
	return nil
}

func (x *AuthFrame) GetError() *AuthError {
	if x != nil {
		if x, ok := x.Kind.(*AuthFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAuthFrame_Kind interface {
	isAuthFrame_Kind()
}

type AuthFrame_HostAuthInit struct {
	HostAuthInit *HostAuthInit `protobuf:"bytes,1,opt,name=host_auth_init,json=hostAuthInit,proto3,oneof"`
}

type AuthFrame_ServerAuth struct {
	ServerAuth *ServerAuth `protobuf:"bytes,2,opt,name=server_auth,json=serverAuth,proto3,oneof"`
}

type AuthFrame_ClientAuthRequest struct {
	ClientAuthRequest *ClientAuthRequest `protobuf:"bytes,3,opt,name=client_auth_request,json=clientAuthRequest,proto3,oneof"`
}

type AuthFrame_ClientAuthResponse struct {
	ClientAuthResponse *ClientAuthResponse `protobuf:"bytes,4,opt,name=client_auth_response,json=clientAuthResponse,proto3,oneof"`
}

type AuthFrame_Error struct {
	Error *AuthError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*AuthFrame_HostAuthInit) isAuthFrame_Kind() {}

func (*AuthFrame_ServerAuth) isAuthFrame_Kind() {}

func (*AuthFrame_ClientAuthRequest) isAuthFrame_Kind() {}

func (*AuthFrame_ClientAuthResponse) isAuthFrame_Kind() {}

func (*AuthFrame_Error) isAuthFrame_Kind() {}

type HostAuthInit struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MygoshAuthVersion string                 `protobuf:"bytes,1,opt,name=mygosh_auth_version,json=mygoshAuthVersion,proto3" json:"mygosh_auth_version,omitempty"`
	ClientNonce       []byte                 `protobuf:"bytes,2,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ReferenceIdentity string                 `protobuf:"bytes,3,opt,name=reference_identity,json=referenceIdentity,proto3" json:"reference_identity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostAuthInit) Reset() {
	*x = HostAuthInit{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAuthInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAuthInit) ProtoMessage() {}

func (x *HostAuthInit) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAuthInit.ProtoReflect.Descriptor instead.
func (*HostAuthInit) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *HostAuthInit) GetMygoshAuthVersion() string {
	if x != nil {
		return x.MygoshAuthVersion
	}
	return ""
}

func (x *HostAuthInit) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *HostAuthInit) GetReferenceIdentity() string {
	if x != nil {
		return x.ReferenceIdentity
	}
	return ""
}

type ServerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerHostKey []byte                 `protobuf:"bytes,1,opt,name=server_host_key,json=serverHostKey,proto3" json:"server_host_key,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAuth) Reset() {
	*x = ServerAuth{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAuth) ProtoMessage() {}

func (x *ServerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAuth.ProtoReflect.Descriptor instead.
func (*ServerAuth) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ServerAuth) GetServerHostKey() []byte {
	if x != nil {
		return x.ServerHostKey
	}
	return nil
}

func (x *ServerAuth) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *ServerAuth) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ClientAuthRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Username              string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientPublicKeyOrCert []byte                 `protobuf:"bytes,2,opt,name=client_public_key_or_cert,json=clientPublicKeyOrCert,proto3" json:"client_public_key_or_cert,omitempty"`
	ClientSigAlg          string                 `protobuf:"bytes,3,opt,name=client_sig_alg,json=clientSigAlg,proto3" json:"client_sig_alg,omitempty"`
	Signature             []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientAuthRequest) Reset() {
	*x = ClientAuthRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthRequest) ProtoMessage() {}

func (x *ClientAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthRequest.ProtoReflect.Descriptor instead.
func (*ClientAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ClientAuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientAuthRequest) GetClientPublicKeyOrCert() []byte {
	if x != nil {
		return x.ClientPublicKeyOrCert
	}
	return nil
}

func (x *ClientAuthRequest) GetClientSigAlg() string {
	if x != nil {
		return x.ClientSigAlg
	}
	return ""
}

func (x *ClientAuthRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ClientAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ClientAuthResponse_Ok
	//	*ClientAuthResponse_Reject
	Result        isClientAuthResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAuthResponse) Reset() {
	*x = ClientAuthResponse{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthResponse) ProtoMessage() {}

func (x *ClientAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthResponse.ProtoReflect.Descriptor instead.
func (*ClientAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ClientAuthResponse) GetResult() isClientAuthResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ClientAuthResponse) GetOk() *AuthSuccess {
	if x != nil {
		if x, ok := x.Result.(*ClientAuthResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ClientAuthResponse) GetReject() *AuthReject {
	if x != nil {
		if x, ok := x.Result.(*ClientAuthResponse_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isClientAuthResponse_Result interface {
	isClientAuthResponse_Result()
}

type ClientAuthResponse_Ok struct {
	Ok *AuthSuccess `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type ClientAuthResponse_Reject struct {
	Reject *AuthReject `protobuf:"bytes,2,opt,name=reject,proto3,oneof"`
}

func (*ClientAuthResponse_Ok) isClientAuthResponse_Result() {}

func (*ClientAuthResponse_Reject) isClientAuthResponse_Result() {}

type AuthSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSuccess) Reset() {
	*x = AuthSuccess{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSuccess) ProtoMessage() {}

func (x *AuthSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSuccess.ProtoReflect.Descriptor instead.
func (*AuthSuccess) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

type AuthReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReject) Reset() {
	*x = AuthReject{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReject) ProtoMessage() {}

func (x *AuthReject) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReject.ProtoReflect.Descriptor instead.
func (*AuthReject) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthReject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerAuthToSign struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Context          string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ChannelBinding   []byte                 `protobuf:"bytes,2,opt,name=channel_binding,json=channelBinding,proto3" json:"channel_binding,omitempty"`
	HostAuthInitHash []byte                 `protobuf:"bytes,3,opt,name=host_auth_init_hash,json=hostAuthInitHash,proto3" json:"host_auth_init_hash,omitempty"`
	ServerHostKey    []byte                 `protobuf:"bytes,4,opt,name=server_host_key,json=serverHostKey,proto3" json:"server_host_key,omitempty"`
	ServerNonce      []byte                 `protobuf:"bytes,5,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerAuthToSign) Reset() {
	*x = ServerAuthToSign{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAuthToSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAuthToSign) ProtoMessage() {}

func (x *ServerAuthToSign) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAuthToSign.ProtoReflect.Descriptor instead.
func (*ServerAuthToSign) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ServerAuthToSign) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ServerAuthToSign) GetChannelBinding() []byte {
	if x != nil {
		return x.ChannelBinding
	}
	return nil
}

func (x *ServerAuthToSign) GetHostAuthInitHash() []byte {
	if x != nil {
		return x.HostAuthInitHash
	}
	return nil
}

func (x *ServerAuthToSign) GetServerHostKey() []byte {
	if x != nil {
		return x.ServerHostKey
	}
	return nil
}

func (x *ServerAuthToSign) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

type ClientAuthToSign struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Context               string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ChannelBinding        []byte                 `protobuf:"bytes,2,opt,name=channel_binding,json=channelBinding,proto3" json:"channel_binding,omitempty"`
	HostAuthInitHash      []byte                 `protobuf:"bytes,3,opt,name=host_auth_init_hash,json=hostAuthInitHash,proto3" json:"host_auth_init_hash,omitempty"`
	ServerAuthHash        []byte                 `protobuf:"bytes,4,opt,name=server_auth_hash,json=serverAuthHash,proto3" json:"server_auth_hash,omitempty"`
	Username              string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	ClientPublicKeyOrCert []byte                 `protobuf:"bytes,6,opt,name=client_public_key_or_cert,json=clientPublicKeyOrCert,proto3" json:"client_public_key_or_cert,omitempty"`
	ClientSigAlg          string                 `protobuf:"bytes,7,opt,name=client_sig_alg,json=clientSigAlg,proto3" json:"client_sig_alg,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientAuthToSign) Reset() {
	*x = ClientAuthToSign{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthToSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthToSign) ProtoMessage() {}

func (x *ClientAuthToSign) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthToSign.ProtoReflect.Descriptor instead.
func (*ClientAuthToSign) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ClientAuthToSign) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ClientAuthToSign) GetChannelBinding() []byte {
	if x != nil {
		return x.ChannelBinding
	}
	return nil
}

func (x *ClientAuthToSign) GetHostAuthInitHash() []byte {
	if x != nil {
		return x.HostAuthInitHash
	}
	return nil
}

func (x *ClientAuthToSign) GetServerAuthHash() []byte {
	if x != nil {
		return x.ServerAuthHash
	}
	return nil
}

func (x *ClientAuthToSign) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientAuthToSign) GetClientPublicKeyOrCert() []byte {
	if x != nil {
		return x.ClientPublicKeyOrCert
	}
	return nil
}

func (x *ClientAuthToSign) GetClientSigAlg() string {
	if x != nil {
		return x.ClientSigAlg
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\x1a\x1bbuf/validate/validate.proto\"\xcd\x02\n" +
	"\tAuthFrame\x12:\n" +
	"\x0ehost_auth_init\x18\x01 \x01(\v2\x12.auth.HostAuthInitH\x00R\fhostAuthInit\x123\n" +
	"\vserver_auth\x18\x02 \x01(\v2\x10.auth.ServerAuthH\x00R\n" +
	"serverAuth\x12I\n" +
	"\x13client_auth_request\x18\x03 \x01(\v2\x17.auth.ClientAuthRequestH\x00R\x11clientAuthRequest\x12L\n" +
	"\x14client_auth_response\x18\x04 \x01(\v2\x18.auth.ClientAuthResponseH\x00R\x12clientAuthResponse\x12'\n" +
	"\x05error\x18\x05 \x01(\v2\x0f.auth.AuthErrorH\x00R\x05errorB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\xab\x01\n" +
	"\fHostAuthInit\x127\n" +
	"\x13mygosh_auth_version\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11mygoshAuthVersion\x12*\n" +
	"\fclient_nonce\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\vclientNonce\x126\n" +
	"\x12reference_identity\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11referenceIdentity\"\x90\x01\n" +
	"\n" +
	"ServerAuth\x12/\n" +
	"\x0fserver_host_key\x18\x01 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\rserverHostKey\x12*\n" +
	"\fserver_nonce\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\vserverNonce\x12%\n" +
	"\tsignature\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\tsignature\"\xd1\x01\n" +
	"\x11ClientAuthRequest\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12A\n" +
	"\x19client_public_key_or_cert\x18\x02 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\x15clientPublicKeyOrCert\x12-\n" +
	"\x0eclient_sig_alg\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fclientSigAlg\x12%\n" +
	"\tsignature\x18\x04 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\tsignature\"v\n" +
	"\x12ClientAuthResponse\x12#\n" +
	"\x02ok\x18\x01 \x01(\v2\x11.auth.AuthSuccessH\x00R\x02ok\x12*\n" +
	"\x06reject\x18\x02 \x01(\v2\x10.auth.AuthRejectH\x00R\x06rejectB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\r\n" +
	"\vAuthSuccess\"C\n" +
	"\n" +
	"AuthReject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\"B\n" +
	"\tAuthError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\"\xfc\x01\n" +
	"\x10ServerAuthToSign\x12!\n" +
	"\acontext\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acontext\x120\n" +
	"\x0fchannel_binding\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\x0echannelBinding\x126\n" +
	"\x13host_auth_init_hash\x18\x03 \x01(\fB\a\xbaH\x04z\x02h R\x10hostAuthInitHash\x12/\n" +
	"\x0fserver_host_key\x18\x04 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\rserverHostKey\x12*\n" +
	"\fserver_nonce\x18\x05 \x01(\fB\a\xbaH\x04z\x02h R\vserverNonce\"\xe9\x02\n" +
	"\x10ClientAuthToSign\x12!\n" +
	"\acontext\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acontext\x120\n" +
	"\x0fchannel_binding\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\x0echannelBinding\x126\n" +
	"\x13host_auth_init_hash\x18\x03 \x01(\fB\a\xbaH\x04z\x02h R\x10hostAuthInitHash\x121\n" +
	"\x10server_auth_hash\x18\x04 \x01(\fB\a\xbaH\x04z\x02h R\x0eserverAuthHash\x12#\n" +
	"\busername\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12A\n" +
	"\x19client_public_key_or_cert\x18\x06 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\x15clientPublicKeyOrCert\x12-\n" +
	"\x0eclient_sig_alg\x18\a \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fclientSigAlgB3Z1github.com/Mikadore/mygosh/lib/auth/authpb;authpbb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_auth_proto_goTypes = []any{
	(*AuthFrame)(nil),          // 0: auth.AuthFrame
	(*HostAuthInit)(nil),       // 1: auth.HostAuthInit
	(*ServerAuth)(nil),         // 2: auth.ServerAuth
	(*ClientAuthRequest)(nil),  // 3: auth.ClientAuthRequest
	(*ClientAuthResponse)(nil), // 4: auth.ClientAuthResponse
	(*AuthSuccess)(nil),        // 5: auth.AuthSuccess
	(*AuthReject)(nil),         // 6: auth.AuthReject
	(*AuthError)(nil),          // 7: auth.AuthError
	(*ServerAuthToSign)(nil),   // 8: auth.ServerAuthToSign
	(*ClientAuthToSign)(nil),   // 9: auth.ClientAuthToSign
}
var file_auth_auth_proto_depIdxs = []int32{
	1, // 0: auth.AuthFrame.host_auth_init:type_name -> auth.HostAuthInit
	2, // 1: auth.AuthFrame.server_auth:type_name -> auth.ServerAuth
	3, // 2: auth.AuthFrame.client_auth_request:type_name -> auth.ClientAuthRequest
	4, // 3: auth.AuthFrame.client_auth_response:type_name -> auth.ClientAuthResponse
	7, // 4: auth.AuthFrame.error:type_name -> auth.AuthError
	5, // 5: auth.ClientAuthResponse.ok:type_name -> auth.AuthSuccess
	6, // 6: auth.ClientAuthResponse.reject:type_name -> auth.AuthReject
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	file_auth_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthFrame_HostAuthInit)(nil),
		(*AuthFrame_ServerAuth)(nil),
		(*AuthFrame_ClientAuthRequest)(nil),
		(*AuthFrame_ClientAuthResponse)(nil),
		(*AuthFrame_Error)(nil),
	}
	file_auth_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*ClientAuthResponse_Ok)(nil),
		(*ClientAuthResponse_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
