// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mygosh/wire/v1/auth.proto

package wirepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostAuthInit struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MygoshAuthVersion string                 `protobuf:"bytes,1,opt,name=mygosh_auth_version,json=mygoshAuthVersion,proto3" json:"mygosh_auth_version,omitempty"`
	ClientNonce       []byte                 `protobuf:"bytes,2,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ReferenceIdentity string                 `protobuf:"bytes,3,opt,name=reference_identity,json=referenceIdentity,proto3" json:"reference_identity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostAuthInit) Reset() {
	*x = HostAuthInit{}
	mi := &file_mygosh_wire_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAuthInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAuthInit) ProtoMessage() {}

func (x *HostAuthInit) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAuthInit.ProtoReflect.Descriptor instead.
func (*HostAuthInit) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *HostAuthInit) GetMygoshAuthVersion() string {
	if x != nil {
		return x.MygoshAuthVersion
	}
	return ""
}

func (x *HostAuthInit) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *HostAuthInit) GetReferenceIdentity() string {
	if x != nil {
		return x.ReferenceIdentity
	}
	return ""
}

type ServerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerHostKey []byte                 `protobuf:"bytes,1,opt,name=server_host_key,json=serverHostKey,proto3" json:"server_host_key,omitempty"`
	ServerNonce   []byte                 `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAuth) Reset() {
	*x = ServerAuth{}
	mi := &file_mygosh_wire_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAuth) ProtoMessage() {}

func (x *ServerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAuth.ProtoReflect.Descriptor instead.
func (*ServerAuth) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ServerAuth) GetServerHostKey() []byte {
	if x != nil {
		return x.ServerHostKey
	}
	return nil
}

func (x *ServerAuth) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *ServerAuth) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ClientAuthRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Username              string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Service               string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	ClientPublicKeyOrCert []byte                 `protobuf:"bytes,3,opt,name=client_public_key_or_cert,json=clientPublicKeyOrCert,proto3" json:"client_public_key_or_cert,omitempty"`
	ClientSigAlg          string                 `protobuf:"bytes,4,opt,name=client_sig_alg,json=clientSigAlg,proto3" json:"client_sig_alg,omitempty"`
	Signature             []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientAuthRequest) Reset() {
	*x = ClientAuthRequest{}
	mi := &file_mygosh_wire_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthRequest) ProtoMessage() {}

func (x *ClientAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthRequest.ProtoReflect.Descriptor instead.
func (*ClientAuthRequest) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ClientAuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientAuthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ClientAuthRequest) GetClientPublicKeyOrCert() []byte {
	if x != nil {
		return x.ClientPublicKeyOrCert
	}
	return nil
}

func (x *ClientAuthRequest) GetClientSigAlg() string {
	if x != nil {
		return x.ClientSigAlg
	}
	return ""
}

func (x *ClientAuthRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_mygosh_wire_v1_auth_proto protoreflect.FileDescriptor

const file_mygosh_wire_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19mygosh/wire/v1/auth.proto\x12\x0emygosh.wire.v1\x1a\x1bbuf/validate/validate.proto\"\xab\x01\n" +
	"\fHostAuthInit\x127\n" +
	"\x13mygosh_auth_version\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11mygoshAuthVersion\x12*\n" +
	"\fclient_nonce\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\vclientNonce\x126\n" +
	"\x12reference_identity\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11referenceIdentity\"\x90\x01\n" +
	"\n" +
	"ServerAuth\x12/\n" +
	"\x0fserver_host_key\x18\x01 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\rserverHostKey\x12*\n" +
	"\fserver_nonce\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\vserverNonce\x12%\n" +
	"\tsignature\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\tsignature\"\xf4\x01\n" +
	"\x11ClientAuthRequest\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12!\n" +
	"\aservice\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aservice\x12A\n" +
	"\x19client_public_key_or_cert\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\x15clientPublicKeyOrCert\x12-\n" +
	"\x0eclient_sig_alg\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fclientSigAlg\x12%\n" +
	"\tsignature\x18\x05 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\tsignatureB3Z1github.com/Mikadore/mygosh/lib/wire/wirepb;wirepbb\x06proto3"

var (
	file_mygosh_wire_v1_auth_proto_rawDescOnce sync.Once
	file_mygosh_wire_v1_auth_proto_rawDescData []byte
)

func file_mygosh_wire_v1_auth_proto_rawDescGZIP() []byte {
	file_mygosh_wire_v1_auth_proto_rawDescOnce.Do(func() {
		file_mygosh_wire_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mygosh_wire_v1_auth_proto_rawDesc), len(file_mygosh_wire_v1_auth_proto_rawDesc)))
	})
	return file_mygosh_wire_v1_auth_proto_rawDescData
}

var file_mygosh_wire_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mygosh_wire_v1_auth_proto_goTypes = []any{
	(*HostAuthInit)(nil),      // 0: mygosh.wire.v1.HostAuthInit
	(*ServerAuth)(nil),        // 1: mygosh.wire.v1.ServerAuth
	(*ClientAuthRequest)(nil), // 2: mygosh.wire.v1.ClientAuthRequest
}
var file_mygosh_wire_v1_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mygosh_wire_v1_auth_proto_init() }
func file_mygosh_wire_v1_auth_proto_init() {
	if File_mygosh_wire_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mygosh_wire_v1_auth_proto_rawDesc), len(file_mygosh_wire_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mygosh_wire_v1_auth_proto_goTypes,
		DependencyIndexes: file_mygosh_wire_v1_auth_proto_depIdxs,
		MessageInfos:      file_mygosh_wire_v1_auth_proto_msgTypes,
	}.Build()
	File_mygosh_wire_v1_auth_proto = out.File
	file_mygosh_wire_v1_auth_proto_goTypes = nil
	file_mygosh_wire_v1_auth_proto_depIdxs = nil
}
