// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mygosh/wire/v1/messages.proto

package wirepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Envelope_Open
	//	*Envelope_OpenOk
	//	*Envelope_Data
	//	*Envelope_Err
	//	*Envelope_Resize
	//	*Envelope_Close
	//	*Envelope_ExitStatus
	Kind          isEnvelope_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetKind() isEnvelope_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Envelope) GetOpen() *OpenRequest {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *Envelope) GetOpenOk() *OpenResponse {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_OpenOk); ok {
			return x.OpenOk
		}
	}
	return nil
}

func (x *Envelope) GetData() *Data {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Envelope) GetErr() *Error {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_Err); ok {
			return x.Err
		}
	}
	return nil
}

func (x *Envelope) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Envelope) GetClose() *Close {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Envelope) GetExitStatus() *ExitStatus {
	if x != nil {
		if x, ok := x.Kind.(*Envelope_ExitStatus); ok {
			return x.ExitStatus
		}
	}
	return nil
}

type isEnvelope_Kind interface {
	isEnvelope_Kind()
}

type Envelope_Open struct {
	Open *OpenRequest `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type Envelope_OpenOk struct {
	OpenOk *OpenResponse `protobuf:"bytes,2,opt,name=open_ok,json=openOk,proto3,oneof"`
}

type Envelope_Data struct {
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Envelope_Err struct {
	Err *Error `protobuf:"bytes,4,opt,name=err,proto3,oneof"`
}

type Envelope_Resize struct {
	Resize *Resize `protobuf:"bytes,5,opt,name=resize,proto3,oneof"`
}

type Envelope_Close struct {
	Close *Close `protobuf:"bytes,6,opt,name=close,proto3,oneof"`
}

type Envelope_ExitStatus struct {
	ExitStatus *ExitStatus `protobuf:"bytes,7,opt,name=exit_status,json=exitStatus,proto3,oneof"`
}

func (*Envelope_Open) isEnvelope_Kind() {}

func (*Envelope_OpenOk) isEnvelope_Kind() {}

func (*Envelope_Data) isEnvelope_Kind() {}

func (*Envelope_Err) isEnvelope_Kind() {}

func (*Envelope_Resize) isEnvelope_Kind() {}

func (*Envelope_Close) isEnvelope_Kind() {}

func (*Envelope_ExitStatus) isEnvelope_Kind() {}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *OpenRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *OpenRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *OpenRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OpenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Close) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ExitStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitStatus) Reset() {
	*x = ExitStatus{}
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitStatus) ProtoMessage() {}

func (x *ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_wire_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitStatus.ProtoReflect.Descriptor instead.
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return file_mygosh_wire_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ExitStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_mygosh_wire_v1_messages_proto protoreflect.FileDescriptor

const file_mygosh_wire_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dmygosh/wire/v1/messages.proto\x12\x0emygosh.wire.v1\x1a\x1bbuf/validate/validate.proto\"\xfc\x02\n" +
	"\bEnvelope\x121\n" +
	"\x04open\x18\x01 \x01(\v2\x1b.mygosh.wire.v1.OpenRequestH\x00R\x04open\x127\n" +
	"\aopen_ok\x18\x02 \x01(\v2\x1c.mygosh.wire.v1.OpenResponseH\x00R\x06openOk\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x14.mygosh.wire.v1.DataH\x00R\x04data\x12)\n" +
	"\x03err\x18\x04 \x01(\v2\x15.mygosh.wire.v1.ErrorH\x00R\x03err\x120\n" +
	"\x06resize\x18\x05 \x01(\v2\x16.mygosh.wire.v1.ResizeH\x00R\x06resize\x12-\n" +
	"\x05close\x18\x06 \x01(\v2\x15.mygosh.wire.v1.CloseH\x00R\x05close\x12=\n" +
	"\vexit_status\x18\a \x01(\v2\x1a.mygosh.wire.v1.ExitStatusH\x00R\n" +
	"exitStatusB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"_\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x1d\n" +
	"\x04rows\x18\x02 \x01(\rB\t\xbaH\x06*\x04\x18\xff\xff\x03R\x04rows\x12\x1d\n" +
	"\x04cols\x18\x03 \x01(\rB\t\xbaH\x06*\x04\x18\xff\xff\x03R\x04cols\"-\n" +
	"\fOpenResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\">\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\"J\n" +
	"\x06Resize\x12\x1f\n" +
	"\x04rows\x18\x01 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04rows\x12\x1f\n" +
	"\x04cols\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04cols\"\x1f\n" +
	"\x05Close\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\" \n" +
	"\n" +
	"ExitStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04codeB3Z1github.com/Mikadore/mygosh/lib/wire/wirepb;wirepbb\x06proto3"

var (
	file_mygosh_wire_v1_messages_proto_rawDescOnce sync.Once
	file_mygosh_wire_v1_messages_proto_rawDescData []byte
)

func file_mygosh_wire_v1_messages_proto_rawDescGZIP() []byte {
	file_mygosh_wire_v1_messages_proto_rawDescOnce.Do(func() {
		file_mygosh_wire_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mygosh_wire_v1_messages_proto_rawDesc), len(file_mygosh_wire_v1_messages_proto_rawDesc)))
	})
	return file_mygosh_wire_v1_messages_proto_rawDescData
}

var file_mygosh_wire_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mygosh_wire_v1_messages_proto_goTypes = []any{
	(*Envelope)(nil),     // 0: mygosh.wire.v1.Envelope
	(*OpenRequest)(nil),  // 1: mygosh.wire.v1.OpenRequest
	(*OpenResponse)(nil), // 2: mygosh.wire.v1.OpenResponse
	(*Data)(nil),         // 3: mygosh.wire.v1.Data
	(*Error)(nil),        // 4: mygosh.wire.v1.Error
	(*Resize)(nil),       // 5: mygosh.wire.v1.Resize
	(*Close)(nil),        // 6: mygosh.wire.v1.Close
	(*ExitStatus)(nil),   // 7: mygosh.wire.v1.ExitStatus
}
var file_mygosh_wire_v1_messages_proto_depIdxs = []int32{
	1, // 0: mygosh.wire.v1.Envelope.open:type_name -> mygosh.wire.v1.OpenRequest
	2, // 1: mygosh.wire.v1.Envelope.open_ok:type_name -> mygosh.wire.v1.OpenResponse
	3, // 2: mygosh.wire.v1.Envelope.data:type_name -> mygosh.wire.v1.Data
	4, // 3: mygosh.wire.v1.Envelope.err:type_name -> mygosh.wire.v1.Error
	5, // 4: mygosh.wire.v1.Envelope.resize:type_name -> mygosh.wire.v1.Resize
	6, // 5: mygosh.wire.v1.Envelope.close:type_name -> mygosh.wire.v1.Close
	7, // 6: mygosh.wire.v1.Envelope.exit_status:type_name -> mygosh.wire.v1.ExitStatus
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_mygosh_wire_v1_messages_proto_init() }
func file_mygosh_wire_v1_messages_proto_init() {
	if File_mygosh_wire_v1_messages_proto != nil {
		return
	}
	file_mygosh_wire_v1_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Open)(nil),
		(*Envelope_OpenOk)(nil),
		(*Envelope_Data)(nil),
		(*Envelope_Err)(nil),
		(*Envelope_Resize)(nil),
		(*Envelope_Close)(nil),
		(*Envelope_ExitStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mygosh_wire_v1_messages_proto_rawDesc), len(file_mygosh_wire_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mygosh_wire_v1_messages_proto_goTypes,
		DependencyIndexes: file_mygosh_wire_v1_messages_proto_depIdxs,
		MessageInfos:      file_mygosh_wire_v1_messages_proto_msgTypes,
	}.Build()
	File_mygosh_wire_v1_messages_proto = out.File
	file_mygosh_wire_v1_messages_proto_goTypes = nil
	file_mygosh_wire_v1_messages_proto_depIdxs = nil
}
