// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mygosh/service/v1/session_service.proto

package servicepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PtyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyRequest) Reset() {
	*x = PtyRequest{}
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyRequest) ProtoMessage() {}

func (x *PtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyRequest.ProtoReflect.Descriptor instead.
func (*PtyRequest) Descriptor() ([]byte, []int) {
	return file_mygosh_service_v1_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *PtyRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *PtyRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PtyRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ShellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_mygosh_service_v1_session_service_proto_rawDescGZIP(), []int{1}
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_mygosh_service_v1_session_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type WindowChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowChange) Reset() {
	*x = WindowChange{}
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowChange) ProtoMessage() {}

func (x *WindowChange) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowChange.ProtoReflect.Descriptor instead.
func (*WindowChange) Descriptor() ([]byte, []int) {
	return file_mygosh_service_v1_session_service_proto_rawDescGZIP(), []int{3}
}

func (x *WindowChange) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WindowChange) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ExitStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitStatus) Reset() {
	*x = ExitStatus{}
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitStatus) ProtoMessage() {}

func (x *ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mygosh_service_v1_session_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitStatus.ProtoReflect.Descriptor instead.
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return file_mygosh_service_v1_session_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExitStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_mygosh_service_v1_session_service_proto protoreflect.FileDescriptor

const file_mygosh_service_v1_session_service_proto_rawDesc = "" +
	"\n" +
	"'mygosh/service/v1/session_service.proto\x12\x11mygosh.service.v1\x1a\x1bbuf/validate/validate.proto\"^\n" +
	"\n" +
	"PtyRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x1d\n" +
	"\x04rows\x18\x02 \x01(\rB\t\xbaH\x06*\x04\x18\xff\xff\x03R\x04rows\x12\x1d\n" +
	"\x04cols\x18\x03 \x01(\rB\t\xbaH\x06*\x04\x18\xff\xff\x03R\x04cols\"\x0e\n" +
	"\fShellRequest\"0\n" +
	"\vExecRequest\x12!\n" +
	"\acommand\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acommand\"P\n" +
	"\fWindowChange\x12\x1f\n" +
	"\x04rows\x18\x01 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04rows\x12\x1f\n" +
	"\x04cols\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04cols\" \n" +
	"\n" +
	"ExitStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04codeB<Z:github.com/Mikadore/mygosh/lib/service/servicepb;servicepbb\x06proto3"

var (
	file_mygosh_service_v1_session_service_proto_rawDescOnce sync.Once
	file_mygosh_service_v1_session_service_proto_rawDescData []byte
)

func file_mygosh_service_v1_session_service_proto_rawDescGZIP() []byte {
	file_mygosh_service_v1_session_service_proto_rawDescOnce.Do(func() {
		file_mygosh_service_v1_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mygosh_service_v1_session_service_proto_rawDesc), len(file_mygosh_service_v1_session_service_proto_rawDesc)))
	})
	return file_mygosh_service_v1_session_service_proto_rawDescData
}

var file_mygosh_service_v1_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mygosh_service_v1_session_service_proto_goTypes = []any{
	(*PtyRequest)(nil),   // 0: mygosh.service.v1.PtyRequest
	(*ShellRequest)(nil), // 1: mygosh.service.v1.ShellRequest
	(*ExecRequest)(nil),  // 2: mygosh.service.v1.ExecRequest
	(*WindowChange)(nil), // 3: mygosh.service.v1.WindowChange
	(*ExitStatus)(nil),   // 4: mygosh.service.v1.ExitStatus
}
var file_mygosh_service_v1_session_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mygosh_service_v1_session_service_proto_init() }
func file_mygosh_service_v1_session_service_proto_init() {
	if File_mygosh_service_v1_session_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mygosh_service_v1_session_service_proto_rawDesc), len(file_mygosh_service_v1_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mygosh_service_v1_session_service_proto_goTypes,
		DependencyIndexes: file_mygosh_service_v1_session_service_proto_depIdxs,
		MessageInfos:      file_mygosh_service_v1_session_service_proto_msgTypes,
	}.Build()
	File_mygosh_service_v1_session_service_proto = out.File
	file_mygosh_service_v1_session_service_proto_goTypes = nil
	file_mygosh_service_v1_session_service_proto_depIdxs = nil
}
