// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: command/command.proto

package commandpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ClientFrame_Start
	//	*ClientFrame_Stdin
	//	*ClientFrame_StdinEof
	//	*ClientFrame_WindowChange
	Kind          isClientFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetKind() isClientFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ClientFrame) GetStart() *Start {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ClientFrame) GetStdin() *Stdin {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ClientFrame) GetStdinEof() *StdinEof {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_StdinEof); ok {
			return x.StdinEof
		}
	}
	return nil
}

func (x *ClientFrame) GetWindowChange() *WindowChange {
	if x != nil {
		if x, ok := x.Kind.(*ClientFrame_WindowChange); ok {
			return x.WindowChange
		}
	}
	return nil
}

type isClientFrame_Kind interface {
	isClientFrame_Kind()
}

type ClientFrame_Start struct {
	Start *Start `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ClientFrame_Stdin struct {
	Stdin *Stdin `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ClientFrame_StdinEof struct {
	StdinEof *StdinEof `protobuf:"bytes,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

type ClientFrame_WindowChange struct {
	WindowChange *WindowChange `protobuf:"bytes,4,opt,name=window_change,json=windowChange,proto3,oneof"`
}

func (*ClientFrame_Start) isClientFrame_Kind() {}

func (*ClientFrame_Stdin) isClientFrame_Kind() {}

func (*ClientFrame_StdinEof) isClientFrame_Kind() {}

func (*ClientFrame_WindowChange) isClientFrame_Kind() {}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerFrame_StartResult
	//	*ServerFrame_Stdout
	//	*ServerFrame_Stderr
	//	*ServerFrame_Exit
	Kind          isServerFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetKind() isServerFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerFrame) GetStartResult() *StartResult {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_StartResult); ok {
			return x.StartResult
		}
	}
	return nil
}

func (x *ServerFrame) GetStdout() *Stdout {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ServerFrame) GetStderr() *Stderr {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ServerFrame) GetExit() *Exit {
	if x != nil {
		if x, ok := x.Kind.(*ServerFrame_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isServerFrame_Kind interface {
	isServerFrame_Kind()
}

type ServerFrame_StartResult struct {
	StartResult *StartResult `protobuf:"bytes,1,opt,name=start_result,json=startResult,proto3,oneof"`
}

type ServerFrame_Stdout struct {
	Stdout *Stdout `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type ServerFrame_Stderr struct {
	Stderr *Stderr `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type ServerFrame_Exit struct {
	Exit *Exit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

func (*ServerFrame_StartResult) isServerFrame_Kind() {}

func (*ServerFrame_Stdout) isServerFrame_Kind() {}

func (*ServerFrame_Stderr) isServerFrame_Kind() {}

func (*ServerFrame_Exit) isServerFrame_Kind() {}

type Start struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*Start_Shell
	//	*Start_Exec
	Target        isStart_Target `protobuf_oneof:"target"`
	Pty           *Pty           `protobuf:"bytes,4,opt,name=pty,proto3" json:"pty,omitempty"`
	Environment   []*Environment `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *Start) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Start) GetTarget() isStart_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Start) GetShell() *Shell {
	if x != nil {
		if x, ok := x.Target.(*Start_Shell); ok {
			return x.Shell
		}
	}
	return nil
}

func (x *Start) GetExec() *Exec {
	if x != nil {
		if x, ok := x.Target.(*Start_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Start) GetPty() *Pty {
	if x != nil {
		return x.Pty
	}
	return nil
}

func (x *Start) GetEnvironment() []*Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type isStart_Target interface {
	isStart_Target()
}

type Start_Shell struct {
	Shell *Shell `protobuf:"bytes,2,opt,name=shell,proto3,oneof"`
}

type Start_Exec struct {
	Exec *Exec `protobuf:"bytes,3,opt,name=exec,proto3,oneof"`
}

func (*Start_Shell) isStart_Target() {}

func (*Start_Exec) isStart_Target() {}

type Shell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shell) Reset() {
	*x = Shell{}
	mi := &file_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shell) ProtoMessage() {}

func (x *Shell) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shell.ProtoReflect.Descriptor instead.
func (*Shell) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{3}
}

type Exec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exec) Reset() {
	*x = Exec{}
	mi := &file_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exec) ProtoMessage() {}

func (x *Exec) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exec.ProtoReflect.Descriptor instead.
func (*Exec) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *Exec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Pty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terminal      string                 `protobuf:"bytes,1,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       uint32                 `protobuf:"varint,3,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pty) Reset() {
	*x = Pty{}
	mi := &file_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pty) ProtoMessage() {}

func (x *Pty) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pty.ProtoReflect.Descriptor instead.
func (*Pty) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *Pty) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

func (x *Pty) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Pty) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Stdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stdin) Reset() {
	*x = Stdin{}
	mi := &file_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stdin) ProtoMessage() {}

func (x *Stdin) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stdin.ProtoReflect.Descriptor instead.
func (*Stdin) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *Stdin) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StdinEof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdinEof) Reset() {
	*x = StdinEof{}
	mi := &file_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdinEof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdinEof) ProtoMessage() {}

func (x *StdinEof) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdinEof.ProtoReflect.Descriptor instead.
func (*StdinEof) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{8}
}

type WindowChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       uint32                 `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowChange) Reset() {
	*x = WindowChange{}
	mi := &file_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowChange) ProtoMessage() {}

func (x *WindowChange) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowChange.ProtoReflect.Descriptor instead.
func (*WindowChange) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *WindowChange) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WindowChange) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type StartResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResult) Reset() {
	*x = StartResult{}
	mi := &file_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResult) ProtoMessage() {}

func (x *StartResult) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResult.ProtoReflect.Descriptor instead.
func (*StartResult) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *StartResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StartResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StartResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Stdout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stdout) Reset() {
	*x = Stdout{}
	mi := &file_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stdout) ProtoMessage() {}

func (x *Stdout) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stdout.ProtoReflect.Descriptor instead.
func (*Stdout) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{11}
}

func (x *Stdout) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Stderr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stderr) Reset() {
	*x = Stderr{}
	mi := &file_command_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stderr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stderr) ProtoMessage() {}

func (x *Stderr) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stderr.ProtoReflect.Descriptor instead.
func (*Stderr) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{12}
}

func (x *Stderr) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Exit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*Exit_Status
	//	*Exit_Signal
	//	*Exit_RuntimeFailure
	Result        isExit_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exit) Reset() {
	*x = Exit{}
	mi := &file_command_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{13}
}

func (x *Exit) GetResult() isExit_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Exit) GetStatus() int32 {
	if x != nil {
		if x, ok := x.Result.(*Exit_Status); ok {
			return x.Status
		}
	}
	return 0
}

func (x *Exit) GetSignal() string {
	if x != nil {
		if x, ok := x.Result.(*Exit_Signal); ok {
			return x.Signal
		}
	}
	return ""
}

func (x *Exit) GetRuntimeFailure() *RuntimeFailure {
	if x != nil {
		if x, ok := x.Result.(*Exit_RuntimeFailure); ok {
			return x.RuntimeFailure
		}
	}
	return nil
}

type isExit_Result interface {
	isExit_Result()
}

type Exit_Status struct {
	Status int32 `protobuf:"varint,1,opt,name=status,proto3,oneof"`
}

type Exit_Signal struct {
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

type Exit_RuntimeFailure struct {
	RuntimeFailure *RuntimeFailure `protobuf:"bytes,3,opt,name=runtime_failure,json=runtimeFailure,proto3,oneof"`
}

func (*Exit_Status) isExit_Result() {}

func (*Exit_Signal) isExit_Result() {}

func (*Exit_RuntimeFailure) isExit_Result() {}

type RuntimeFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeFailure) Reset() {
	*x = RuntimeFailure{}
	mi := &file_command_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeFailure) ProtoMessage() {}

func (x *RuntimeFailure) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeFailure.ProtoReflect.Descriptor instead.
func (*RuntimeFailure) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{14}
}

func (x *RuntimeFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_command_command_proto protoreflect.FileDescriptor

const file_command_command_proto_rawDesc = "" +
	"\n" +
	"\x15command/command.proto\x12\acommand\x1a\x1bbuf/validate/validate.proto\"\xdc\x01\n" +
	"\vClientFrame\x12&\n" +
	"\x05start\x18\x01 \x01(\v2\x0e.command.StartH\x00R\x05start\x12&\n" +
	"\x05stdin\x18\x02 \x01(\v2\x0e.command.StdinH\x00R\x05stdin\x120\n" +
	"\tstdin_eof\x18\x03 \x01(\v2\x11.command.StdinEofH\x00R\bstdinEof\x12<\n" +
	"\rwindow_change\x18\x04 \x01(\v2\x15.command.WindowChangeH\x00R\fwindowChangeB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\xd2\x01\n" +
	"\vServerFrame\x129\n" +
	"\fstart_result\x18\x01 \x01(\v2\x14.command.StartResultH\x00R\vstartResult\x12)\n" +
	"\x06stdout\x18\x02 \x01(\v2\x0f.command.StdoutH\x00R\x06stdout\x12)\n" +
	"\x06stderr\x18\x03 \x01(\v2\x0f.command.StderrH\x00R\x06stderr\x12#\n" +
	"\x04exit\x18\x04 \x01(\v2\r.command.ExitH\x00R\x04exitB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\xfc\x01\n" +
	"\x05Start\x122\n" +
	"\x10protocol_version\x18\x01 \x01(\rB\a\xbaH\x04*\x02\b\x01R\x0fprotocolVersion\x12&\n" +
	"\x05shell\x18\x02 \x01(\v2\x0e.command.ShellH\x00R\x05shell\x12#\n" +
	"\x04exec\x18\x03 \x01(\v2\r.command.ExecH\x00R\x04exec\x12\x1e\n" +
	"\x03pty\x18\x04 \x01(\v2\f.command.PtyR\x03pty\x12A\n" +
	"\venvironment\x18\x05 \x03(\v2\x14.command.EnvironmentB\t\xbaH\x06\x92\x01\x03\x10\x80\x01R\venvironmentB\x0f\n" +
	"\x06target\x12\x05\xbaH\x02\b\x01\"\a\n" +
	"\x05Shell\"-\n" +
	"\x04Exec\x12%\n" +
	"\acommand\x18\x01 \x01(\tB\v\xbaH\br\x06\x10\x01\x18\x80\xc0\x01R\acommand\"s\n" +
	"\x03Pty\x12$\n" +
	"\bterminal\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\bterminal\x12\x1f\n" +
	"\x04rows\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04rows\x12%\n" +
	"\acolumns\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\acolumns\"N\n" +
	"\vEnvironment\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x04name\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x01R\x05value\")\n" +
	"\x05Stdin\x12 \n" +
	"\x04data\x18\x01 \x01(\fB\f\xbaH\tz\a\x10\x01\x18\x80\x80\x80\x04R\x04data\"\n" +
	"\n" +
	"\bStdinEof\"V\n" +
	"\fWindowChange\x12\x1f\n" +
	"\x04rows\x18\x01 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04rows\x12%\n" +
	"\acolumns\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\acolumns\"j\n" +
	"\vStartResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\x04code\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\x04code\x12\"\n" +
	"\amessage\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\amessage\"*\n" +
	"\x06Stdout\x12 \n" +
	"\x04data\x18\x01 \x01(\fB\f\xbaH\tz\a\x10\x01\x18\x80\x80\x80\x04R\x04data\"*\n" +
	"\x06Stderr\x12 \n" +
	"\x04data\x18\x01 \x01(\fB\f\xbaH\tz\a\x10\x01\x18\x80\x80\x80\x04R\x04data\"\x9a\x01\n" +
	"\x04Exit\x12\x18\n" +
	"\x06status\x18\x01 \x01(\x05H\x00R\x06status\x12#\n" +
	"\x06signal\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@H\x00R\x06signal\x12B\n" +
	"\x0fruntime_failure\x18\x03 \x01(\v2\x17.command.RuntimeFailureH\x00R\x0eruntimeFailureB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"4\n" +
	"\x0eRuntimeFailure\x12\"\n" +
	"\amessage\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\amessageB<Z:github.com/Mikadore/mygosh/lib/command/commandpb;commandpbb\x06proto3"

var (
	file_command_command_proto_rawDescOnce sync.Once
	file_command_command_proto_rawDescData []byte
)

func file_command_command_proto_rawDescGZIP() []byte {
	file_command_command_proto_rawDescOnce.Do(func() {
		file_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_command_proto_rawDesc), len(file_command_command_proto_rawDesc)))
	})
	return file_command_command_proto_rawDescData
}

var file_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_command_command_proto_goTypes = []any{
	(*ClientFrame)(nil),    // 0: command.ClientFrame
	(*ServerFrame)(nil),    // 1: command.ServerFrame
	(*Start)(nil),          // 2: command.Start
	(*Shell)(nil),          // 3: command.Shell
	(*Exec)(nil),           // 4: command.Exec
	(*Pty)(nil),            // 5: command.Pty
	(*Environment)(nil),    // 6: command.Environment
	(*Stdin)(nil),          // 7: command.Stdin
	(*StdinEof)(nil),       // 8: command.StdinEof
	(*WindowChange)(nil),   // 9: command.WindowChange
	(*StartResult)(nil),    // 10: command.StartResult
	(*Stdout)(nil),         // 11: command.Stdout
	(*Stderr)(nil),         // 12: command.Stderr
	(*Exit)(nil),           // 13: command.Exit
	(*RuntimeFailure)(nil), // 14: command.RuntimeFailure
}
var file_command_command_proto_depIdxs = []int32{
	2,  // 0: command.ClientFrame.start:type_name -> command.Start
	7,  // 1: command.ClientFrame.stdin:type_name -> command.Stdin
	8,  // 2: command.ClientFrame.stdin_eof:type_name -> command.StdinEof
	9,  // 3: command.ClientFrame.window_change:type_name -> command.WindowChange
	10, // 4: command.ServerFrame.start_result:type_name -> command.StartResult
	11, // 5: command.ServerFrame.stdout:type_name -> command.Stdout
	12, // 6: command.ServerFrame.stderr:type_name -> command.Stderr
	13, // 7: command.ServerFrame.exit:type_name -> command.Exit
	3,  // 8: command.Start.shell:type_name -> command.Shell
	4,  // 9: command.Start.exec:type_name -> command.Exec
	5,  // 10: command.Start.pty:type_name -> command.Pty
	6,  // 11: command.Start.environment:type_name -> command.Environment
	14, // 12: command.Exit.runtime_failure:type_name -> command.RuntimeFailure
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_command_command_proto_init() }
func file_command_command_proto_init() {
	if File_command_command_proto != nil {
		return
	}
	file_command_command_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Start)(nil),
		(*ClientFrame_Stdin)(nil),
		(*ClientFrame_StdinEof)(nil),
		(*ClientFrame_WindowChange)(nil),
	}
	file_command_command_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_StartResult)(nil),
		(*ServerFrame_Stdout)(nil),
		(*ServerFrame_Stderr)(nil),
		(*ServerFrame_Exit)(nil),
	}
	file_command_command_proto_msgTypes[2].OneofWrappers = []any{
		(*Start_Shell)(nil),
		(*Start_Exec)(nil),
	}
	file_command_command_proto_msgTypes[13].OneofWrappers = []any{
		(*Exit_Status)(nil),
		(*Exit_Signal)(nil),
		(*Exit_RuntimeFailure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_command_proto_rawDesc), len(file_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_command_proto_goTypes,
		DependencyIndexes: file_command_command_proto_depIdxs,
		MessageInfos:      file_command_command_proto_msgTypes,
	}.Build()
	File_command_command_proto = out.File
	file_command_command_proto_goTypes = nil
	file_command_command_proto_depIdxs = nil
}
